### ISSUE TITLE
Exercise 2,5: Add .zip Library  failed

### ISSUE THREAD

**Issue by krkrosenbergtech** [WefaaRobotics/Smorphi#6]
Given: Followed all steps in Exercise 1 and including Exercise 2, 4.

When: Following Exercise 2, 5. Sketch > Include Library > Add .zip Library...

Then: Error message appears
Error: 13 INTERNAL: Library install failed: moving extracted archive to destination dir: library not valid

Note: It is not possible for me to include the library as a .zip or to unzil and run a test as the smorphi.cpp implementation is missing.

**Comment by VickyKrishna** [comment]
For a quick solution, the issue could be resolved by unzipping the folder, and copying all the folders except "Smorphi Assembly Manual" and "exercise" folders into Documents-> Arduino -> libraries.

We are updating the repository to directly include the library as .zip format.
